// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package schema

import (
	"context"

	"github.com/google/uuid"
)

const insertClient = `-- name: InsertClient :one
INSERT INTO
    clients (der_public_key, redirect_uri)
VALUES
    ($1, $2) RETURNING id, der_public_key, redirect_uri
`

type InsertClientParams struct {
	DerPublicKey []byte `json:"der_public_key"`
	RedirectUri  string `json:"redirect_uri"`
}

func (q *Queries) InsertClient(ctx context.Context, arg InsertClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, insertClient, arg.DerPublicKey, arg.RedirectUri)
	var i Client
	err := row.Scan(&i.ID, &i.DerPublicKey, &i.RedirectUri)
	return i, err
}

const selectClientByID = `-- name: SelectClientByID :one
SELECT
    id, der_public_key, redirect_uri
FROM
    clients
WHERE
    id = $1
`

func (q *Queries) SelectClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, selectClientByID, id)
	var i Client
	err := row.Scan(&i.ID, &i.DerPublicKey, &i.RedirectUri)
	return i, err
}
