// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jwk_sets.sql

package schema

import (
	"context"

	"github.com/google/uuid"
)

const insertJwkSet = `-- name: InsertJwkSet :one
INSERT INTO
    jwk_sets (der_private_key)
VALUES
    ($1) RETURNING id, der_private_key
`

func (q *Queries) InsertJwkSet(ctx context.Context, derPrivateKey []byte) (JwkSet, error) {
	row := q.db.QueryRow(ctx, insertJwkSet, derPrivateKey)
	var i JwkSet
	err := row.Scan(&i.ID, &i.DerPrivateKey)
	return i, err
}

const selectJwkSetByID = `-- name: SelectJwkSetByID :one
SELECT
    id, der_private_key
FROM
    jwk_sets
WHERE
    id = $1
`

func (q *Queries) SelectJwkSetByID(ctx context.Context, id uuid.UUID) (JwkSet, error) {
	row := q.db.QueryRow(ctx, selectJwkSetByID, id)
	var i JwkSet
	err := row.Scan(&i.ID, &i.DerPrivateKey)
	return i, err
}

const selectJwkSets = `-- name: SelectJwkSets :many
SELECT
    id, der_private_key
FROM
    jwk_sets
`

func (q *Queries) SelectJwkSets(ctx context.Context) ([]JwkSet, error) {
	rows, err := q.db.Query(ctx, selectJwkSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JwkSet
	for rows.Next() {
		var i JwkSet
		if err := rows.Scan(&i.ID, &i.DerPrivateKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
