// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package schema

import (
	"github.com/google/uuid"
)

type Client struct {
	ID           uuid.UUID `json:"id"`
	DerPublicKey []byte    `json:"der_public_key"`
	RedirectUri  string    `json:"redirect_uri"`
}

type JwkSet struct {
	ID            uuid.UUID `json:"id"`
	DerPrivateKey []byte    `json:"der_private_key"`
}
