//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerScopes = "Bearer.Scopes"
)

// Defines values for TokenErrorError.
const (
	InvalidClient        TokenErrorError = "invalid_client"
	InvalidGrant         TokenErrorError = "invalid_grant"
	InvalidRequest       TokenErrorError = "invalid_request"
	InvalidScope         TokenErrorError = "invalid_scope"
	UnauthorizedClient   TokenErrorError = "unauthorized_client"
	UnsupportedGrantType TokenErrorError = "unsupported_grant_type"
)

// Defines values for TokenRequestGrantType.
const (
	TokenRequestGrantTypeAuthorizationCode TokenRequestGrantType = "authorization_code"
	TokenRequestGrantTypeRefreshToken      TokenRequestGrantType = "refresh_token"
)

// Defines values for AuthorizeParamsResponseType.
const (
	Code AuthorizeParamsResponseType = "code"
)

// Defines values for AuthorizeParamsScope.
const (
	Openid AuthorizeParamsScope = "openid"
)

// Defines values for RevokeFormdataBodyTokenTypeHint.
const (
	RevokeFormdataBodyTokenTypeHintAccessToken  RevokeFormdataBodyTokenTypeHint = "access_token"
	RevokeFormdataBodyTokenTypeHintRefreshToken RevokeFormdataBodyTokenTypeHint = "refresh_token"
)

// CertsResponse defines model for CertsResponse.
type CertsResponse struct {
	Keys []JWKSet `json:"keys"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// JWKSet defines model for JWKSet.
type JWKSet struct {
	Alg string `json:"alg"`
	E   string `json:"e"`
	Kid string `json:"kid"`
	Kty string `json:"kty"`
	N   string `json:"n"`
	Use string `json:"use"`
}

// OpenIDConfiguration https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata
type OpenIDConfiguration struct {
	// AuthorizationEndpoint http://localhost:8787/authorize
	AuthorizationEndpoint            string   `json:"authorization_endpoint"`
	IdTokenSigningAlgValuesSupported []string `json:"id_token_signing_alg_values_supported"`

	// Issuer http://localhost:8787
	Issuer string `json:"issuer"`

	// JwksUri http://localhost:8787/certs
	JwksUri                string   `json:"jwks_uri"`
	ResponseTypesSupported []string `json:"response_types_supported"`
	SubjectTypesSupported  []string `json:"subject_types_supported"`

	// TokenEndpoint http://localhost:8787/token
	TokenEndpoint string `json:"token_endpoint"`

	// UserinfoEndpoint http://localhost:8787/userinfo
	UserinfoEndpoint string `json:"userinfo_endpoint"`
}

// TokenError defines model for TokenError.
type TokenError struct {
	Error            TokenErrorError `json:"error"`
	ErrorDescription string          `json:"error_description"`
	ErrorUri         string          `json:"error_uri"`
}

// TokenErrorError defines model for TokenError.Error.
type TokenErrorError string

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	// ClientAssertion needs when grant_type is authorization_code. ref https://datatracker.ietf.org/doc/html/rfc7523#section-2.2
	ClientAssertion *string `json:"client_assertion,omitempty"`

	// ClientId needs when grant_type is authorization_code
	ClientId *string `json:"client_id,omitempty"`

	// ClientSecret needs when grant_type is authorization_code
	ClientSecret *string `json:"client_secret,omitempty"`

	// Code needs when grant_type is authorization_code
	Code *string `json:"code,omitempty"`

	// GrantType grant_type
	GrantType TokenRequestGrantType `json:"grant_type"`

	// RedirectUri neews when grant_type is authorization_code
	RedirectUri *string `json:"redirect_uri,omitempty"`

	// RefreshToken needs when grant_type is refresh_token
	RefreshToken *string `json:"refresh_token,omitempty"`

	// Scope optional
	Scope *string `json:"scope,omitempty"`
}

// TokenRequestGrantType grant_type
type TokenRequestGrantType string

// TokenResponse https://openid-foundation-japan.github.io/openid-connect-core-1_0.ja.html#TokenResponse
type TokenResponse struct {
	// AccessToken access_token
	AccessToken string `json:"access_token"`

	// ExpiresIn expires_in
	ExpiresIn int `json:"expires_in"`

	// IdToken id_token
	IdToken string `json:"id_token"`

	// RefreshToken refresh_token
	RefreshToken string `json:"refresh_token"`

	// TokenType token_type
	TokenType string `json:"token_type"`
}

// UserInfoResponse defines model for UserInfoResponse.
type UserInfoResponse struct {
	Email string `json:"email"`
	Sub   string `json:"sub"`
}

// FinalizeAssertionJSONBody defines parameters for FinalizeAssertion.
type FinalizeAssertionJSONBody = interface{}

// FinalizeAssertionParams defines parameters for FinalizeAssertion.
type FinalizeAssertionParams struct {
	// UnderscoreUnderscoreAssertion session
	UnderscoreUnderscoreAssertion string `form:"__assertion__" json:"__assertion__"`
}

// AuthorizeParams defines parameters for Authorize.
type AuthorizeParams struct {
	// ResponseType response_type
	ResponseType AuthorizeParamsResponseType `form:"response_type" json:"response_type"`

	// ClientId client_id
	ClientId openapi_types.UUID `form:"client_id" json:"client_id"`

	// RedirectUri redirect_uri
	RedirectUri *string `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`

	// Scope openid
	Scope *AuthorizeParamsScope `form:"scope,omitempty" json:"scope,omitempty"`

	// State state
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// AuthorizeParamsResponseType defines parameters for Authorize.
type AuthorizeParamsResponseType string

// AuthorizeParamsScope defines parameters for Authorize.
type AuthorizeParamsScope string

// CallbackParams defines parameters for Callback.
type CallbackParams struct {
	// UnderscoreUnderscoreAuthorize auth session
	UnderscoreUnderscoreAuthorize string `form:"__authorize__" json:"__authorize__"`

	// UnderscoreUnderscoreSession user session
	UnderscoreUnderscoreSession string `form:"__session__" json:"__session__"`
}

// RevokeFormdataBody defines parameters for Revoke.
type RevokeFormdataBody struct {
	Token         string                           `form:"token" json:"token"`
	TokenTypeHint *RevokeFormdataBodyTokenTypeHint `form:"token_type_hint,omitempty" json:"token_type_hint,omitempty"`
}

// RevokeFormdataBodyTokenTypeHint defines parameters for Revoke.
type RevokeFormdataBodyTokenTypeHint string

// FinalizeAssertionJSONRequestBody defines body for FinalizeAssertion for application/json ContentType.
type FinalizeAssertionJSONRequestBody = FinalizeAssertionJSONBody

// RevokeFormdataRequestBody defines body for Revoke for application/x-www-form-urlencoded ContentType.
type RevokeFormdataRequestBody RevokeFormdataBody

// TokenFormdataRequestBody defines body for Token for application/x-www-form-urlencoded ContentType.
type TokenFormdataRequestBody = TokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health Checl
	// (GET /)
	Health(w http.ResponseWriter, r *http.Request)
	// OpenID Provider Configuration
	// (GET /.well-known/openid-configuration)
	OpenIDConfiguration(w http.ResponseWriter, r *http.Request)
	// Initialize Assertion
	// (GET /assertion)
	InitializeAssertion(w http.ResponseWriter, r *http.Request)
	// Finalize Assertion
	// (POST /assertion)
	FinalizeAssertion(w http.ResponseWriter, r *http.Request, params FinalizeAssertionParams)
	// Authorization Endpoint
	// (GET /authorize)
	Authorize(w http.ResponseWriter, r *http.Request, params AuthorizeParams)
	// Callback Endpoint
	// (GET /callback)
	Callback(w http.ResponseWriter, r *http.Request, params CallbackParams)
	// JWK Set
	// (GET /certs)
	Jwks(w http.ResponseWriter, r *http.Request)
	// Revocation Endpoint
	// (POST /revoke)
	Revoke(w http.ResponseWriter, r *http.Request)
	// Token Endpoint
	// (POST /token)
	Token(w http.ResponseWriter, r *http.Request)
	// UserInfo Endpoint
	// (GET /userinfo)
	Userinfo(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OpenIDConfiguration operation middleware
func (siw *ServerInterfaceWrapper) OpenIDConfiguration(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OpenIDConfiguration(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InitializeAssertion operation middleware
func (siw *ServerInterfaceWrapper) InitializeAssertion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InitializeAssertion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FinalizeAssertion operation middleware
func (siw *ServerInterfaceWrapper) FinalizeAssertion(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params FinalizeAssertionParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("__assertion__"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "__assertion__", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "__assertion__", Err: err})
				return
			}
			params.UnderscoreUnderscoreAssertion = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "__assertion__"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FinalizeAssertion(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Authorize operation middleware
func (siw *ServerInterfaceWrapper) Authorize(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthorizeParams

	// ------------- Required query parameter "response_type" -------------

	if paramValue := r.URL.Query().Get("response_type"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "response_type"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "response_type", r.URL.Query(), &params.ResponseType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "response_type", Err: err})
		return
	}

	// ------------- Required query parameter "client_id" -------------

	if paramValue := r.URL.Query().Get("client_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "client_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "client_id", r.URL.Query(), &params.ClientId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_id", Err: err})
		return
	}

	// ------------- Optional query parameter "redirect_uri" -------------

	err = runtime.BindQueryParameter("form", true, false, "redirect_uri", r.URL.Query(), &params.RedirectUri)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_uri", Err: err})
		return
	}

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Authorize(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Callback operation middleware
func (siw *ServerInterfaceWrapper) Callback(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CallbackParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("__authorize__"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "__authorize__", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "__authorize__", Err: err})
				return
			}
			params.UnderscoreUnderscoreAuthorize = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "__authorize__"})
			return
		}
	}

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("__session__"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "__session__", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "__session__", Err: err})
				return
			}
			params.UnderscoreUnderscoreSession = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "__session__"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Callback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Jwks operation middleware
func (siw *ServerInterfaceWrapper) Jwks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Jwks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Revoke operation middleware
func (siw *ServerInterfaceWrapper) Revoke(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Revoke(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Token operation middleware
func (siw *ServerInterfaceWrapper) Token(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Token(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Userinfo operation middleware
func (siw *ServerInterfaceWrapper) Userinfo(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Userinfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/{$}", wrapper.Health)
	m.HandleFunc("GET "+options.BaseURL+"/.well-known/openid-configuration", wrapper.OpenIDConfiguration)
	m.HandleFunc("GET "+options.BaseURL+"/assertion", wrapper.InitializeAssertion)
	m.HandleFunc("POST "+options.BaseURL+"/assertion", wrapper.FinalizeAssertion)
	m.HandleFunc("GET "+options.BaseURL+"/authorize", wrapper.Authorize)
	m.HandleFunc("GET "+options.BaseURL+"/callback", wrapper.Callback)
	m.HandleFunc("GET "+options.BaseURL+"/certs", wrapper.Jwks)
	m.HandleFunc("POST "+options.BaseURL+"/revoke", wrapper.Revoke)
	m.HandleFunc("POST "+options.BaseURL+"/token", wrapper.Token)
	m.HandleFunc("GET "+options.BaseURL+"/userinfo", wrapper.Userinfo)

	return m
}

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200Response struct {
}

func (response Health200Response) VisitHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type HealthdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response HealthdefaultJSONResponse) VisitHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type OpenIDConfigurationRequestObject struct {
}

type OpenIDConfigurationResponseObject interface {
	VisitOpenIDConfigurationResponse(w http.ResponseWriter) error
}

type OpenIDConfiguration200JSONResponse OpenIDConfiguration

func (response OpenIDConfiguration200JSONResponse) VisitOpenIDConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type OpenIDConfigurationdefaultResponse struct {
	StatusCode int
}

func (response OpenIDConfigurationdefaultResponse) VisitOpenIDConfigurationResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type InitializeAssertionRequestObject struct {
}

type InitializeAssertionResponseObject interface {
	VisitInitializeAssertionResponse(w http.ResponseWriter) error
}

type InitializeAssertion200ResponseHeaders struct {
	SetCookie string
}

type InitializeAssertion200JSONResponse struct {
	Body    interface{}
	Headers InitializeAssertion200ResponseHeaders
}

func (response InitializeAssertion200JSONResponse) VisitInitializeAssertionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type InitializeAssertiondefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response InitializeAssertiondefaultJSONResponse) VisitInitializeAssertionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FinalizeAssertionRequestObject struct {
	Params FinalizeAssertionParams
	Body   *FinalizeAssertionJSONRequestBody
}

type FinalizeAssertionResponseObject interface {
	VisitFinalizeAssertionResponse(w http.ResponseWriter) error
}

type FinalizeAssertion200ResponseHeaders struct {
	SetCookie string
}

type FinalizeAssertion200JSONResponse struct {
	Body    interface{}
	Headers FinalizeAssertion200ResponseHeaders
}

func (response FinalizeAssertion200JSONResponse) VisitFinalizeAssertionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type FinalizeAssertiondefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response FinalizeAssertiondefaultJSONResponse) VisitFinalizeAssertionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type AuthorizeRequestObject struct {
	Params AuthorizeParams
}

type AuthorizeResponseObject interface {
	VisitAuthorizeResponse(w http.ResponseWriter) error
}

type Authorize302ResponseHeaders struct {
	Location  string
	SetCookie string
}

type Authorize302Response struct {
	Headers Authorize302ResponseHeaders
}

func (response Authorize302Response) VisitAuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(302)
	return nil
}

type Authorize400JSONResponse string

func (response Authorize400JSONResponse) VisitAuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AuthorizedefaultResponse struct {
	StatusCode int
}

func (response AuthorizedefaultResponse) VisitAuthorizeResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type CallbackRequestObject struct {
	Params CallbackParams
}

type CallbackResponseObject interface {
	VisitCallbackResponse(w http.ResponseWriter) error
}

type Callback302ResponseHeaders struct {
	Location  string
	SetCookie string
}

type Callback302Response struct {
	Headers Callback302ResponseHeaders
}

func (response Callback302Response) VisitCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(302)
	return nil
}

type CallbackdefaultResponse struct {
	StatusCode int
}

func (response CallbackdefaultResponse) VisitCallbackResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type JwksRequestObject struct {
}

type JwksResponseObject interface {
	VisitJwksResponse(w http.ResponseWriter) error
}

type Jwks200JSONResponse CertsResponse

func (response Jwks200JSONResponse) VisitJwksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type JwksdefaultResponse struct {
	StatusCode int
}

func (response JwksdefaultResponse) VisitJwksResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type RevokeRequestObject struct {
	Body *RevokeFormdataRequestBody
}

type RevokeResponseObject interface {
	VisitRevokeResponse(w http.ResponseWriter) error
}

type Revoke200Response struct {
}

func (response Revoke200Response) VisitRevokeResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type RevokedefaultResponse struct {
	StatusCode int
}

func (response RevokedefaultResponse) VisitRevokeResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type TokenRequestObject struct {
	Body *TokenFormdataRequestBody
}

type TokenResponseObject interface {
	VisitTokenResponse(w http.ResponseWriter) error
}

type Token200ResponseHeaders struct {
	CacheControl string
	Pragma       string
}

type Token200JSONResponse struct {
	Body    TokenResponse
	Headers Token200ResponseHeaders
}

func (response Token200JSONResponse) VisitTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.Header().Set("Pragma", fmt.Sprint(response.Headers.Pragma))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type Token400JSONResponse TokenError

func (response Token400JSONResponse) VisitTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type TokendefaultResponse struct {
	StatusCode int
}

func (response TokendefaultResponse) VisitTokenResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

type UserinfoRequestObject struct {
}

type UserinfoResponseObject interface {
	VisitUserinfoResponse(w http.ResponseWriter) error
}

type Userinfo200JSONResponse UserInfoResponse

func (response Userinfo200JSONResponse) VisitUserinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Userinfo401Response struct {
}

func (response Userinfo401Response) VisitUserinfoResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type UserinfodefaultResponse struct {
	StatusCode int
}

func (response UserinfodefaultResponse) VisitUserinfoResponse(w http.ResponseWriter) error {
	w.WriteHeader(response.StatusCode)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Health Checl
	// (GET /)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)
	// OpenID Provider Configuration
	// (GET /.well-known/openid-configuration)
	OpenIDConfiguration(ctx context.Context, request OpenIDConfigurationRequestObject) (OpenIDConfigurationResponseObject, error)
	// Initialize Assertion
	// (GET /assertion)
	InitializeAssertion(ctx context.Context, request InitializeAssertionRequestObject) (InitializeAssertionResponseObject, error)
	// Finalize Assertion
	// (POST /assertion)
	FinalizeAssertion(ctx context.Context, request FinalizeAssertionRequestObject) (FinalizeAssertionResponseObject, error)
	// Authorization Endpoint
	// (GET /authorize)
	Authorize(ctx context.Context, request AuthorizeRequestObject) (AuthorizeResponseObject, error)
	// Callback Endpoint
	// (GET /callback)
	Callback(ctx context.Context, request CallbackRequestObject) (CallbackResponseObject, error)
	// JWK Set
	// (GET /certs)
	Jwks(ctx context.Context, request JwksRequestObject) (JwksResponseObject, error)
	// Revocation Endpoint
	// (POST /revoke)
	Revoke(ctx context.Context, request RevokeRequestObject) (RevokeResponseObject, error)
	// Token Endpoint
	// (POST /token)
	Token(ctx context.Context, request TokenRequestObject) (TokenResponseObject, error)
	// UserInfo Endpoint
	// (GET /userinfo)
	Userinfo(ctx context.Context, request UserinfoRequestObject) (UserinfoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Health operation middleware
func (sh *strictHandler) Health(w http.ResponseWriter, r *http.Request) {
	var request HealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// OpenIDConfiguration operation middleware
func (sh *strictHandler) OpenIDConfiguration(w http.ResponseWriter, r *http.Request) {
	var request OpenIDConfigurationRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OpenIDConfiguration(ctx, request.(OpenIDConfigurationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OpenIDConfiguration")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OpenIDConfigurationResponseObject); ok {
		if err := validResponse.VisitOpenIDConfigurationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InitializeAssertion operation middleware
func (sh *strictHandler) InitializeAssertion(w http.ResponseWriter, r *http.Request) {
	var request InitializeAssertionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InitializeAssertion(ctx, request.(InitializeAssertionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InitializeAssertion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InitializeAssertionResponseObject); ok {
		if err := validResponse.VisitInitializeAssertionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FinalizeAssertion operation middleware
func (sh *strictHandler) FinalizeAssertion(w http.ResponseWriter, r *http.Request, params FinalizeAssertionParams) {
	var request FinalizeAssertionRequestObject

	request.Params = params

	var body FinalizeAssertionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FinalizeAssertion(ctx, request.(FinalizeAssertionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FinalizeAssertion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FinalizeAssertionResponseObject); ok {
		if err := validResponse.VisitFinalizeAssertionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Authorize operation middleware
func (sh *strictHandler) Authorize(w http.ResponseWriter, r *http.Request, params AuthorizeParams) {
	var request AuthorizeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Authorize(ctx, request.(AuthorizeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Authorize")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthorizeResponseObject); ok {
		if err := validResponse.VisitAuthorizeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Callback operation middleware
func (sh *strictHandler) Callback(w http.ResponseWriter, r *http.Request, params CallbackParams) {
	var request CallbackRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Callback(ctx, request.(CallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Callback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CallbackResponseObject); ok {
		if err := validResponse.VisitCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Jwks operation middleware
func (sh *strictHandler) Jwks(w http.ResponseWriter, r *http.Request) {
	var request JwksRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Jwks(ctx, request.(JwksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Jwks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(JwksResponseObject); ok {
		if err := validResponse.VisitJwksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Revoke operation middleware
func (sh *strictHandler) Revoke(w http.ResponseWriter, r *http.Request) {
	var request RevokeRequestObject

	if err := r.ParseForm(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode formdata: %w", err))
		return
	}
	var body RevokeFormdataRequestBody
	if err := runtime.BindForm(&body, r.Form, nil, nil); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't bind formdata: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Revoke(ctx, request.(RevokeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Revoke")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeResponseObject); ok {
		if err := validResponse.VisitRevokeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Token operation middleware
func (sh *strictHandler) Token(w http.ResponseWriter, r *http.Request) {
	var request TokenRequestObject

	if err := r.ParseForm(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode formdata: %w", err))
		return
	}
	var body TokenFormdataRequestBody
	if err := runtime.BindForm(&body, r.Form, nil, nil); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't bind formdata: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Token(ctx, request.(TokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Token")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TokenResponseObject); ok {
		if err := validResponse.VisitTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Userinfo operation middleware
func (sh *strictHandler) Userinfo(w http.ResponseWriter, r *http.Request) {
	var request UserinfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Userinfo(ctx, request.(UserinfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Userinfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UserinfoResponseObject); ok {
		if err := validResponse.VisitUserinfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
